# Generated by Django 5.0.2 on 2024-02-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minhaimagem',
            name='imagem',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
